qcdnum: qcdnum.f
	gfortran -g  -O2 -fbounds-check -fno-automatic -fno-backslash -fpic -ffixed-line-length-132     qcdnum.f -L/home/radek/moje/qcdnum/lib/ -lqcdnum -lmbutil -L/home/radek/Dropbox/Lund/mcnet/lhapdf/lhadir/lib/ -lLHAPDF -Wl,-rpath=/home/radek/Dropbox/Lund/mcnet/lhapdf/lhadir/lib/  -o qcdnum
